version: '3.8'

services:
  wd-postgres:
    image: mirror.gcr.io/postgres:16.4-alpine
    hostname: wd-postgres
    container_name: wd-postgres
    restart: unless-stopped
    environment:
      # i know that password should be retrieved from secret storage, but for simplicity i put it here
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "127.0.0.1:5433:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data

  wd-app:
    build: .
    environment:
      - # i know that password should be retrieved from secret storage, but for simplicity i put it here
      - WD_DB_PASSWORD=postgres
      - WD_DB_URL=jdbc:postgresql://wd-postgres:5432/postgres
      - WD_DB_USERNAME=postgres
    depends_on:
      - wd-postgres
    ports:
      - "8081:8080"

volumes:
  pg-data:
